version: '3.0'
services:
  json-server:
    image: vimagick/json-server
    command: -h 0.0.0.0 -p 8080 -w /config/db.json
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    restart: always

  app:
    image: app:latest
    build:
      context: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app